from enum import IntEnum


class NotificationType(IntEnum):
    NORMAL = 101
    AWAY = 102  # TODO: 不在メッセージの詳細仕様を確認
    LEAVE = 202
    INVITE = 203
    KICK = 204

    NORMAL = 93001
    ACK = 93004
    RECALL = 93005
    JOIN = 94001
    QUIT = 94002
    SYSTEM = 94003
    CHANNELSYNC = 94004
    KICK = 94005
    BOTMENU = 95001
    LARGE = 93006
    REACTION = 93007
    VOIPJOINCOUNT = 96005
    PTT_MIC_ON = 96007
    PTT_MIC_OFF = 96008

    # 通知メッセージタイプ
    NOTIFICATION_UNKNOWN = 0
    NOTIFICATION_MESSAGE = 1
    NOTIFICATION_CONTACT = 3
    NOTIFICATION_LOCATION = 4
    NOTIFICATION_BOT_MSG = 5
    NOTIFICATION_OFFICIAL_MSG = 6
    NOTIFICATION_CHANNELNOTI_MSG = 7
    NOTIFICATION_RICH_MSG = 8
    NOTIFICATION_NEW_RICH_MSG = 10
    NOTIFICATION_IMG = 11
    NOTIFICATION_AUDIO = 12
    NOTIFICATION_RECORD = 13
    NOTIFICATION_VIDEO = 14

    NOTIFICATION_STICKEROLD = 15 
    NOTIFICATION_STICKERV3 = 18
    # 現在V3が使われているようなので、18をNOTIFICATION_STICKERとして定義
    NOTIFICATION_STICKER = NOTIFICATION_STICKERV3

    NOTIFICATION_FILE = 16
    NOTIFICATION_CALL = 31
    NOTIFICATION_VCALL = 32
    NOTIFICATION_INVITE_DSSHARE = 34
    NOTIFICATION_STOP_DSSHARE = 35
    NOTIFICATION_CANCEL_CALL = 33
    NOTIFICATION_NEW_MAIL = 40
    NOTIFICATION_BADGE = 41
    NOTIFICATION_CAL_SCHD_REMIND = 50
    NOTIFICATION_CAL_TASK_REMIND = 51
    NOTIFICATION_CAL_APPO_INVITE = 52
    NOTIFICATION_CAL_APPO_UPDATE = 53
    NOTIFICATION_CAL_APPO_CANCEL = 54
    NOTIFICATION_API_EXEC_COMMAND = 61
    NOTIFICATION_SERVICE = 100
