from enum import StrEnum


class NotificationSubType(StrEnum):
    MESSAGE_MENTION = "REV_MENTION_MSG"
    NOTE_COMMENT_MENTION = "REV_MENTION_NOTE_COMMENT"
    MESSAGE_INVITE_LINE = "REV_ADD_FRIEND_LINE"
    MESSAGE_INVITE_WORKSAT = "REV_ADD_FRIEND_WORKSAT"
    NOTE_WRITE = "REV_NOTE_WRITE"
    NOTE_NOTICE = "REV_NOTE_NOTICE"
    NOTE_SHARE = "REV_NOTE_SHARE"
    NOTE_MENTION_POST = "REV_MENTION_NOTE_POST"
    MESSAGE_GROUP_VOICE_CALL_INVITE = "REV_GROUP_CALL_INVITE"
    MESSAGE_GROUP_VOICE_CALL_START = "REV_GROUP_CALL_START"
    MESSAGE_GROUP_SCREEN_SHARE_INVITE = "REV_GROUP_RD_INVITE"
    MESSAGE_GROUP_SCREEN_SHARE_START = "REV_GROUP_RD_START"
    MESSAGE_GROUP_VIDEO_CALL_INVITE = "REV_GROUP_VCALL_INVITE"
    MESSAGE_GROUP_VIDEO_CALL_START = "REV_GROUP_VCALL_START"
    MESSAGE_GROUP_VOICE_CALL_AND_SCREEN_SHARE_INVITE = (
        "REV_GROUP_CALL_RD_INVITE"
    )
    MESSAGE_GROUP_VIDEO_CALL_AND_SCREEN_SHARE_INVITE = (
        "REV_GROUP_VCALL_RD_INVITE"
    )
