from enum import IntEnum


class NotificationType(IntEnum):
    # --- General Notification Types ---
    NORMAL = 101
    AWAY = 102
    LEAVE = 202
    INVITE = 203
    KICK = 204

    # --- Message Notification Types ---
    UNKNOWN = 0
    MESSAGE_GENERAL = 1
    MESSAGE_VOIP = 2
    MESSAGE_CONTACT = 3
    MESSAGE_LOCATION = 4
    MESSAGE_BOT_GENERAL = 5
    MESSAGE_BOT_IMG = 6
    MESSAGE_LINK = 7
    MESSAGE_RICH = 8
    MESSAGE_NEW_RICH = 10
    MESSAGE_IMG = 11
    MESSAGE_AUDIO = 12
    MESSAGE_RECORD = 13
    MESSAGE_VIDEO = 14
    MESSAGE_STICKER = 15
    MESSAGE_FILE = 16
    NOTE_POST = 17
    MESSAGE_NEW_STICKER = 18
    NOTE_COMMENT = 19
    MESSAGE_LINK_IMG = 20
    MESSAGE_GROUP_CALL_AND_SCREEN_SHARE = 21
    MESSAGE_BUNDLE = 22
    MESSAGE_BOT_BUTTON_TEMPLATE = 23
    MESSAGE_BOT_LIST_TEMPLATE = 24
    MESSAGE_BOT_RICH_LINK = 25
    MESSAGE_NAME_CARD = 26
    MESSAGE_RICH3 = 27
    NOTE_COMMENT_MENTION = 28
    MESSAGE_TEMPLATE = 29
    MESSAGE_VOICE_CALL = 31
    MESSAGE_VIDEO_CALL = 32
    MESSAGE_CANCEL_CALL = 33
    MESSAGE_SCREEN_SHARE_INVITE = 34
    MESSAGE_SCREEN_SHARE_STOP = 35
    MESSAGE_MENTION = 36
    MESSAGE_PLANET_CALL = 37
    MESSAGE_PLANET_VCALL = 38
    MESSAGE_VOICE = 39
    MAIL_NEW_MAIL = 40
    MESSAGE_BADGE = 41
    MAIL_REMINDER = 42
    MESSAGE_FILE_URL = 44
    MESSAGE_RICH4 = 46
    MESSAGE_BOT_RICH_LINKMSG = 47
    MESSAGE_BOT_RICH_BUTTON_TEMPLATE = 48
    MESSAGE_EXTERNAL_TEMPLATE = 49
    CALENDAR_SCHEDULE_REMIND = 50
    CALENDAR_TASK_REMIND = 51
    CALENDAR_APPOINTMENT_INVITE = 52
    CALENDAR_APPOINTMENT_UPDATE = 53
    CALENDAR_APPOINTMENT_CANCEL = 54
    CALENDAR_RES_CONFLICT = 55
    TASK_DAILY_REMIND = 56
    API_SILENT_PUSH = 60
    API_EXEC_COMMAND = 61
    API_JOIN_ACCEPT = 62
    API_JOIN_REJECT = 63
    MDM_EXEC_COMMAND = 70
    BOARD_POST = 80
    BOARD_NEW_ARTICLE = 81
    BOARD_MUST_READ = 82
    BOARD_RE_NOTIFY = 83
    BOARD_COMMENT = 84
    BOARD_REPLY = 85
    BOARD_MENTION = 86
    BOARD_NOTICE = 87
    DRIVE_SHARE_APPROVEMENT = 90
    MESSAGE_BOT_FLEX = 96
    MESSAGE_CAROUSEL = 97
    MESSAGE_IMAGE_CAROUSEL = 98
    MESSAGE_VOIP2 = 100
    NOTI_MSG_REV_SERVICE_NOTIFICATION = 100
    NOTI_MSG_READ_ALL_SERVICE_NOTIFICATION = 101
    NOTI_MSG_REV_SERVICE_NOTIFICATION_SILENT = 102
    INVITE_EXTERNAL_FRIEND = 108

    # --- Aliases for compatibility ---
    # (コメント: 既存の名称との対応)
    NOTIFICATION_UNKNOWN = UNKNOWN  # UNKNOWN
    NOTIFICATION_MESSAGE = MESSAGE_GENERAL  # MESSAGE_GENERAL
    NOTIFICATION_CONTACT = MESSAGE_CONTACT  # MESSAGE_CONTACT
    NOTIFICATION_LOCATION = MESSAGE_LOCATION  # MESSAGE_LOCATION
    NOTIFICATION_BOT = MESSAGE_BOT_GENERAL  # MESSAGE_BOT_GENERAL
    NOTIFICATION_OFFICIAL = MESSAGE_BOT_IMG  # MESSAGE_BOT_IMG
    NOTIFICATION_CHANNELNOTI = MESSAGE_LINK  # MESSAGE_LINK
    NOTIFICATION_RICH = MESSAGE_RICH  # MESSAGE_RICH
    NOTIFICATION_NEW_RICH = MESSAGE_NEW_RICH  # MESSAGE_NEW_RICH
    NOTIFICATION_IMAGE = MESSAGE_IMG  # MESSAGE_IMG
    NOTIFICATION_AUDIO = MESSAGE_AUDIO  # MESSAGE_AUDIO
    NOTIFICATION_RECORD = MESSAGE_RECORD  # MESSAGE_RECORD
    NOTIFICATION_VIDEO = MESSAGE_VIDEO  # MESSAGE_VIDEO
    NOTIFICATION_STICKER_OLD = MESSAGE_STICKER  # MESSAGE_STICKER
    NOTIFICATION_FILE = MESSAGE_FILE  # MESSAGE_FILE
    NOTIFICATION_STICKER_V3 = MESSAGE_NEW_STICKER  # MESSAGE_NEW_STICKER
    NOTIFICATION_LOCATION_EMOJI = MESSAGE_RICH3  # MESSAGE_RICH3
    NOTIFICATION_CALL = MESSAGE_VOICE_CALL  # MESSAGE_VOICE_CALL
    NOTIFICATION_VCALL = MESSAGE_VIDEO_CALL  # MESSAGE_VIDEO_CALL
    NOTIFICATION_INVITE_DSSHARE = (
        MESSAGE_SCREEN_SHARE_INVITE  # MESSAGE_SCREEN_SHARE_INVITE
    )
    NOTIFICATION_STOP_DSSHARE = (
        MESSAGE_SCREEN_SHARE_STOP  # MESSAGE_SCREEN_SHARE_STOP
    )
    NOTIFICATION_CANCEL_CALL = MESSAGE_CANCEL_CALL  # MESSAGE_CANCEL_CALL
    NOTIFICATION_NEW_MAIL = MAIL_NEW_MAIL  # MAIL_NEW_MAIL
    NOTIFICATION_BADGE = MESSAGE_BADGE  # MESSAGE_BADGE
    NOTIFICATION_CAL_SCHD_REMIND = (
        CALENDAR_SCHEDULE_REMIND  # CALENDAR_SCHEDULE_REMIND
    )
    NOTIFICATION_CAL_TASK_REMIND = CALENDAR_TASK_REMIND  # CALENDAR_TASK_REMIND
    NOTIFICATION_CAL_APPO_INVITE = (
        CALENDAR_APPOINTMENT_INVITE  # CALENDAR_APPOINTMENT_INVITE
    )
    NOTIFICATION_CAL_APPO_UPDATE = (
        CALENDAR_APPOINTMENT_UPDATE  # CALENDAR_APPOINTMENT_UPDATE
    )
    NOTIFICATION_CAL_APPO_CANCEL = (
        CALENDAR_APPOINTMENT_CANCEL  # CALENDAR_APPOINTMENT_CANCEL
    )
    NOTIFICATION_API_EXEC_COMMAND = API_EXEC_COMMAND  # API_EXEC_COMMAND
    NOTIFICATION_SERVICE = (
        NOTI_MSG_REV_SERVICE_NOTIFICATION  # NOTI_MSG_REV_SERVICE_NOTIFICATION
    )

    NOTIFICATION_STICKER = MESSAGE_NEW_STICKER
    # 現在V3が使われているようなので、18をNOTIFICATION_STICKERとして定義
